# Default options for running sunbeam
software-deployment-method:
  - "apptainer"
cores: 'all' # 'all' uses all available cores, you can also specify a number

# Default resource configuration
default-resources:
  - runtime=60
  - mem_mb=1000
  - disk_mb=1000
# set-threads: map rule names to threads
set-threads:
  - kraken2_classify_report=4
  - megahit_paired=4
  - megahit_unpaired=4
  - run_blastn=4
  - run_diamond_blastp=4
  - run_diamond_blastx=4
  - align_to_genome=4