# Template for running on CHOP HPC

qc:
  host_fp: /mnt/isilon/microbiome/analysis/biodata/hosts
sbx_kraken:
  kraken_db_fp: '/mnt/isilon/microbiome/analysis/biodata/kraken2db/standard_20200204'
sbx_gene_clusters:
  genes_fp: /mnt/isilon/microbiome/analysis/biodata/diamondIndexes/v2.1.6.160
sbx_mapping:
  genomes_fp: /mnt/isilon/microbiome/analysis/biodata/bwa_and_bowtie2/six_fungal_genomes
sbx_metaphlan4:
  dbdir: "/mnt/isilon/microbiome/analysis/biodata/metaphlan_databases/v4"
  dbname: "mpa_vOct22_CHOCOPhlAnSGB_202212"