name: Integration Tests

on:
  workflow_call:

  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *'

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        run: |
          pytest tests/e2e/

    test-slurm:
        name: Slurm Test
        runs-on: ubuntu-latest
        services:
            mysql:
              image: mysql:8.0
              env:
                MYSQL_ROOT_PASSWORD: root
              ports:
                - "8888:3306"
              options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
        steps:
            - uses: actions/checkout@v4
            - uses: koesterlab/setup-slurm-action@v1
    
            - name: Install Sunbeam
              run: |
                python -m pip install --upgrade pip
                pip install .[dev]
                pip install snakemake-executor-plugin-slurm
            
            - name: Run Sunbeam
              shell: bash
              run: |
                sunbeam init --data_fp tests/data/reads/ --profile slurm test/
                sunbeam run --default-resources slurm_account=runner --profile test/ test

            - name: Check output
              shell: bash
              run: |
                ls -l .snakemake/slurm_logs/ | grep "rule_test"
    
    test-apptainer:
        name: Apptainer Test
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - uses: eWaterCycle/setup-apptainer@v2
              with:
                apptainer-version: 1.1.2
    
            - name: Install Sunbeam
              shell: bash
              run: |
                python -m pip install --upgrade pip
                pip install .[dev]
    
            - name: Run Sunbeam
              shell: bash
              run: |
                sunbeam init --data_fp tests/data/reads/ --profile apptainer test/
                sunbeam run --profile test/ --docker_tag latest